authors = ["Daniel H Morgan <dhmorgan@protonmail.com>"]
name = "Numerality"
uuid = "0da3f3ca-c42d-11e8-1f89-0fd80279c575"
version = "0.1.0"

[deps]

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
